var date = new Date();
date.setDate(1);
console.log(date);
var year = date.getFullYear();
var month = date.getMonth() - 3;
var day = date.getDate();
var weekdays = ['日','月','火','水','木','金','土'];
var weekday = weekdays[date.getDay()];
var str = "今日は" + year + "年" + month + '月' + day + '日(' + weekday + ')です。';
console.log(str);